export class ProgramCourses {
    name: string;
    image: string;
}

//should be assets instead of assests
// list has image link mistakes - for corrects ones refer to subprograms page 
export const PROGRAMCOURSES: ProgramCourses[] = [
    {name: 'Frontend', image: 'src/assests/program/subprogram/coreui.jpeg'},
    {name: 'Advanced UI', image: 'src/assests/program/subprogram/advancedui.jpg'},
    {name: 'Angular JS', image: 'src/assests/program/subprogram/angular.png'},
    {name: 'React JS', image: 'src/assests/program/subprogram/react2.jpg'},
    {name: 'Vue JS', image: 'src/assests/program/subprogram/vue js.jpeg'},
    {name: 'Java', image: 'src/assests/program/subprogram/java1.jpg'},
    {name: '.Net', image: 'src/assests/program/subprogram/.net2.jpg'},
    {name: 'Node JS', image: 'src/assests/program/subprogram/nodejs1.png'},
    {name: 'Ruby', image: 'src/assests/program/subprogram/ruby1.jpg'},
    {name: 'Python', image: 'src/assests/program/subprogram/python1.jpg'},
    {name: 'Core Java', image: 'src/assests/program/subprogram/core-java.jpg'},
    {name: '.NetCore', image: 'src/assests/program/subprogram/dotnetcore.jpeg'},
    {name: 'MEVN', image: 'src/assests/program/subprogram/mevn.jpg'},
    {name: 'Advanced Java', image: 'src/assests/program/subprogram/advanced1.png'},
    {name: 'MEAN', image: 'src/assests/program/subprogram/mean1.jpg'},
    {name: 'Golang', image: 'src/assests/program/subprogram/golang.png'},
    {name: '.Net', image: 'src/assests/program/subprogram/full stack.net.jpg'},
    {name: 'MEASN', image: 'src/assests/program/subprogram/measn.jpg'},
    {name: 'Manual Testing', image: 'src/assests/program/subprogram/manualtesting.png'},
    {name: 'Automation Testing', image: 'src/assests/program/subprogram/automationtesting.png'},
    {name: 'Cloud Testing', image: 'src/assests/program/subprogram/cloudtesting.png'},
    {name: 'Full Stack Testing', image: 'src/assests/program/subprogram/fullstacktesting.png'},
    {name: 'Flutter', image: 'src/assests/program/subprogram/flutter.jpg'},
    {name: 'Xamarin', image: 'src/assests/program/subprogram/xamarin.jpg'},
    {name: 'Android', image: 'src/assests/program/subprogram/android.jpg'},
    {name: 'Ionic', image: 'src/assests/program/subprogram/ionic1.jpg'},
    {name: 'Onsen UI', image: 'src/assests/program/subprogram/onsenui.jpg'},
    {name: 'React Native', image: 'src/assests/program/subprogram/reactnative.png'},
    {name: 'IOS', image: 'src/assests/program/subprogram/ios.jpg'},
    {name: 'DevOps Foundation', image: 'src/assests/program/subprogram/devopsfound.jpg'},
    {name: 'CHEF', image: 'src/assests/program/subprogram/chef2.jpg'},
    {name: 'Open Stack', image: 'src/assests/program/subprogram/open stack.jpg'},
    {name: 'DevOps Expert', image: 'src/assests/program/subprogram/devopsexpert.jpg'},
    {name: 'Dockers', image: 'src/assests/program/subprogram/docker.jpg'},
    {name: 'Ansible', image: 'src/assests/program/subprogram/ansible2.jpg'},
    {name: 'Kubernetes', image: 'src/assests/program/subprogram/kubernetes.png'},
    {name: 'DS Bootcamp', image: 'src/assests/program/subprogram/dsbootcapm.png'},
    {name: 'Data Science Cerification', image: 'src/assests/program/subprogram/dsc.jpg'},
    {name: 'AI/ML Expert course', image: 'src/assests/program/subprogram/aimlexpert.jpg'},
    {name: 'ML With Python', image: 'src/assests/program/subprogram/ml python.png'},
    {name: 'Natural Language Processing', image: 'src/assests/program/subprogram/nlp.jpg'},
    {name: 'Hadoop', image: 'src/assests/program/subprogram/hadoop.jpg'},
    {name: 'Deep Learning', image: 'src/assests/program/subprogram/deep learning.jpg'},
    {name: 'R Programming', image: 'src/assests/program/subprogram/rpro.jpg'},
    {name: 'Data analytics', image: 'src/assests/program/subprogram/dataanalytics.jpg'},
    {name: 'AI/ML Foundation Course', image: 'src/assests/program/subprogram/aimlfound.jpg'},
    {name: 'AWS Technical Essestial', image: 'src/assests/program/subprogram/aws technical.jpg'},
    {name: 'AWS Developer Associate', image: 'src/assests/program/subprogram/awsdeveloper1.png'},
    {name: 'Microsoft Azure Fundamentals', image: 'src/assests/program/subprogram/Mcf.png'},
    {name: 'AWS Cloud Practitioner', image: 'src/assests/program/subprogram/awscloud2.jpg'},
    {name: 'AWS SysOps Asociate Administrator', image: 'src/assests/program/subprogram/awssysopes.jpg'},
    {name: 'Microsoft Azure Expert Certification', image: 'src/assests/program/subprogram/mae.jpg'},
    {name: 'AWS Solution Architect Associate', image: 'src/assests/program/subprogram/awssolutionarchi2.jpg'},
    {name: 'CISP', image: 'src/assests/program/subprogram/cissp2.jpg'},
    {name: 'CEH', image: 'src/assests/program/subprogram/ceh.jpg'},
    {name: 'CISM', image: 'src/assests/program/subprogram/cism1.jpg'},
    {name: 'CISA', image: 'src/assests/program/subprogram/cisa1.jpg'},
    {name: 'Comptia Security++', image: 'src/assests/program/subprogram/comptiasecurity.jpg'},
    {name: 'Digital Marketing Foundation', image: 'src/assests/program/subprogram/digifound.jpg'},
    {name: 'SMO', image: 'src/assests/program/subprogram/smo1.jpg'},
    {name: 'Adword Expert', image: 'src/assests/program/subprogram/adwordexpert.jpg'},
    {name: 'Digital Marketing Expert', image: 'src/assests/program/subprogram/Digital_marketing_ecpert-1.jpg'},
    {name: 'SCM', image: 'src/assests/program/subprogram/scm.jpg'},
    {name: 'Content Marketing', image: 'src/assests/program/subprogram/contentmarketing.png'},
    {name: 'SEO', image: 'src/assests/program/subprogram/SEO-1.jpg'},
    {name: 'SMM', image: 'src/assests/program/subprogram/smm1.jpg'},
    {name: 'Branding', image: 'src/assests/program/subprogram/branding.jpg'},
    {name: 'Adwords Foundation', image: 'src/assests/program/subprogram/adwordfoun.png'},
    {name: 'SAP', image: 'src/assests/program/subprogram/sap.jpg'},
    {name: 'Oracle', image: 'src/assests/program/subprogram/oracle.jpg'},
    {name: 'Infor LN', image: 'src/assests/program/subprogram/inforln.jpg'},
    {name: 'Rootstack', image: 'src/assests/program/subprogram/rootstack1.jpg'},
    {name: 'Salesforce', image: 'src/assests/program/subprogram/sales force.jpg'},
    {name: 'Service Now', image: 'src/assests/program/subprogram/service-now.png'},
    {name: 'Remedy', image: 'src/assests/program/subprogram/remedy.png'},
    {name: 'Micro Dynamics', image: 'src/assests/program/subprogram/microdynamics.jpg'},
    {name: 'ITIL Foundation', image: 'src/assests/program/subprogram/itil.png'},
    {name: 'PMP', image: 'src/assests/program/subprogram/pmp.jpg'},
    {name: 'PMI-ACP', image: 'src/assests/program/subprogram/PMP-ACP.jpg'},
    {name: 'Agile', image: 'src/assests/program/subprogram/Agile.jpg'},
    {name: 'Prince2', image: 'src/assests/program/subprogram/prince1.jpg'}
  ]