export class SubPrograms {
    title: string;
    description: string;
    courses: string[];
    image: string;
}

export const SUBPROGRAM: SubPrograms[] = [
    {title: 'Frontend', description: 'User interface (UI) developers combine programming, psychology and creative design to craft intuitive controls for software and hardware. ... There is a range of UI development classes and college degrees featuring coursework in the skills needed to become a user interface developer.', courses: ['Frontend', 'Advanced UI', 'Angular JS', 'React JS', 'Vue JS'],image: '../../../assets/program/subprogram/frontend.jpg'},
    {title: 'Backend', description: "Backend development (also stylized as back-end or back end development) is the skill that powers the web. ... Backend development languages handle the 'behind-the-scenes' functionality of web applications. It's code that connects the web to a database, manages user connections, and powers the web application itself.", courses: ['Java', '.Net', 'Node JS', 'Ruby', 'Python'], image: '../../../assets/program/subprogram/backend.jpg'},
    {title: 'Full Stack', description: 'FullStack Developers are computer programmers who are proficient in both front and back end coding. Their primary responsibilities include designing user interactions on websites, developing servers and databases for website functionality and coding for mobile platforms.', courses: ['Core Java', '.NetCore', 'MEVN', 'Advanced Java', 'MEAN', 'Golang', '.Net', 'MEASN', 'Ruby'], image: '../../../assets/program/subprogram/fullstack.jpg'},
    {title: 'Functional Testing', description: 'FUNCTIONAL TESTING is a type of software testing whereby the system is tested against the functional requirements/ specifications. Functions (or features) are tested by feeding them input and examining the output. Functional testing ensures that the requirements are properly satisfied by the application.', courses: ['Manual Testing', 'Automation Testing', 'Cloud Testing', 'Full Stack Testing'], image: '../../../assets/program/subprogram/functionaltesting.png'},
    {title: 'Mobility', description: 'Enterprise mobility is an approach to work in which employees can do their jobs from anywhere using a variety of devices and applications. The term commonly refers to the use of mobile devices, such as smartphones and tablets, for business purposes.', courses: ['Flutter', 'Xamarin', 'Android', 'Ionic', 'Onsen UI', 'React Native', 'IOS'], image: '../../../assets/program/subprogram/mobility.jpg'},
    {title: 'DevOps', description: 'DevOps is a set of practices that automates the processes between software development and IT teams, in order that they can build, test, and release software faster and more reliably. The concept of DevOps is founded on building a culture of collaboration between teams that historically functioned in relative siloes.', courses: ['DevOps Foundation', 'CHEF', 'Open Stack', 'DevOps Expert', 'Dockers', 'Ansible', 'Kubernetes'], image: '../../../assets/program/subprogram/devops.jpg'},
    {title: 'Data Science & AI/ML', description: 'Data science is a "concept to unify statistics, data analysis, machine learning and their related methods" in order to "understand and analyze actual phenomena" with data. It employs techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, and information science.', courses: ['DS Bootcamp', 'Data Science Certification', 'AI/ML Expert Course', 'ML With Python', 'Natural Language Processing', 'Hadoop', 'Deep Learning', 'R Programming', 'Data Analytics', 'AI/ML Foundation Course'], image: '../../../assets/program/subprogram/data science.png'},
    {title: 'Cloud Computing', description: 'Cloud Computing refers to manipulating, configuring, and accessing the hardware and software resources remotely. It offers online data storage, infrastructure, and application. Cloud computing offers platform independency, as the software is not required to be installed locally on the PC.', courses: ['AWS Technical Essential', 'AWS Developer Associate', 'Microsoft Azure Fundamentals', 'AWS Cloud Practitioner', 'AWS SysOps Associate Administrator', 'Microsoft Azure Expert Certification', 'AWS Solution Architect Associate'], image: '../../../assets/program/subprogram/cloud computing.jpg'},
    {title: 'Cyber Security', description: 'Cyber security is the application of technologies, processes and controls to protect systems, networks, programs, devices and data from cyber attacks. It aims to reduce the risk of cyber attacks, and protect against the unauthorised exploitation of systems, networks and technologies.', courses: ['CISSP', 'CEH', 'CISM', 'CISA', 'Comptia Security++'], image: '../../../assets/program/subprogram/cyber security.jpg'},
    {title: 'Digital Marketing', description: 'Digital marketing is the promotion of products or brands via one or more forms of electronic media. Digital marketing is often referred to as online marketing, internet marketing or web marketing.', courses: ['Digital Marketing Foundation', 'SMO', 'Adword Expert', 'Digital Marketing Expert', 'SCM', 'Content Marketing', 'SEO', 'SMM', 'Branding', 'Adwords Foundation'], image: '../../../assets/program/subprogram/digimarketing.jpg'},
    {title: 'ERP', description: 'Enterprise resource planning (ERP) is software designed to help companies store, manage, and use data regarding their daily and regular processes. ERP keeps track of a wealth of information, including payroll, raw materials, business commitments, purchase orders, and capacity for production.', courses: ['SAP', 'Oracle', 'Infor LN', 'Rootstack'], image: 'src/assets/program/subprogram/erp.jpg'},
    {title: 'Information Technology', description: "Information Technology (IT) is the use of computers and software to manage information. It's the career discipline responsible for storing information, protecting information, processing the information, transmitting the information as necessary, and later retrieving information as necessary.", courses: ['Salesforce', 'Service Now', 'Remedy', 'Micro Dynamics'], image: '../../../assets/program/subprogram/it.jpg'},
    {title: 'IT Certification', description: 'An information technology (IT) certificate program provides students with a broad understanding of computer operating systems, information systems, programming, and computer software and hardware. Learn more about program details, career options, and continuing education options.', courses: ['ITIL Foundation', 'PMP', 'PMI-ACP', 'Agile', 'Prince2'], image: '../../../assets/program/subprogram/itcertification.png'}
  ];